version: "3.9"
services:
  backend:
    build:
      context: ./backend
      args:
        - CACHEBUST=1
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - CACHEBUST=2
    ports:
      - "84:80"
    depends_on:
      - backend
    restart: unless-stopped
