name: Build & Push Backend
on:
  push:
    branches: [ "main" ]
    paths: [ "backend/**", ".github/workflows/backend.yml" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3        # <— KELL multi-arch-hoz
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64      # <— FONTOS
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/oc-soccer-backend:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/oc-soccer-backend:main
